In [1]:
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [6]:
#for performing any operation on tuple we need for loop
x=[]
for i in h:
    x.append(i+7)

In [7]:
x

[37, 27, 12, 15, 16]

In [8]:
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [10]:
y=list(s)
d=[]
for i in y:
    d.append(i**2)
s=tuple(d)
s

(36, 4, 9, 81, 49, 25, 64)

In [11]:
s

(36, 4, 9, 81, 49, 25, 64)

In [19]:
x=list(s)
d=[]
for i in x:
    if i>50:
        d.append(i)
    

In [20]:
d

[81, 64]

In [22]:
import numpy as np

In [23]:
arr=np.array([20,30,50,70,40,30,23,98])

In [24]:
arr

array([20, 30, 50, 70, 40, 30, 23, 98])

In [25]:
arr+7

array([ 27,  37,  57,  77,  47,  37,  30, 105])

In [28]:
arr # original array won't be changed

array([20, 30, 50, 70, 40, 30, 23, 98])

In [29]:
#to store changes of array need to store in another variable
t=arr+7
t

array([ 27,  37,  57,  77,  47,  37,  30, 105])

In [30]:
arr

array([20, 30, 50, 70, 40, 30, 23, 98])

In [31]:
arr>50

array([False, False, False,  True, False, False, False,  True])

In [37]:
# directly performing indexing and slicing
arr[2]

50

In [38]:
arr[-4]

40

In [39]:
arr[4]

40

In [40]:
arr[4:8]

array([40, 30, 23, 98])

In [41]:
arr[4:8:2]

array([40, 23])

In [42]:
arr


array([20, 30, 50, 70, 40, 30, 23, 98])

In [43]:
arr[arr>50]  # elements satissfying condition

array([70, 98])

In [44]:
arr>50

array([False, False, False,  True, False, False, False,  True])

In [46]:
arr[arr<=60]

array([20, 30, 50, 40, 30, 23])

In [47]:
k=[36,4,9,81,49,25,64]
k

[36, 4, 9, 81, 49, 25, 64]

In [54]:
index=[]
for i in range(len(k)):
    if k[i]>50:
        index.append(i)
index

[3, 6]

In [55]:
np.where(arr>50) #indexes of elements satisfying condition

(array([3, 7], dtype=int64),)

In [56]:
arr[arr>50]  # elements satissfying condition

array([70, 98])