In [2]:
import pandas as pd
import numpy as np

In [8]:
a=np.random.randint(20,60,15)
a

array([36, 20, 22, 34, 57, 30, 24, 32, 48, 34, 42, 26, 53, 41, 22])

In [9]:
a

array([36, 20, 22, 34, 57, 30, 24, 32, 48, 34, 42, 26, 53, 41, 22])

In [10]:
a[-5:-12]

array([], dtype=int32)

In [11]:
a[-5:-12:-1]

array([42, 34, 48, 32, 24, 30, 57])

In [12]:
a.ndim

1

In [13]:
a[-4]

26

In [25]:
np.random.seed(94)
b=np.random.randint(45,78,(7,6))

In [26]:
b

array([[63, 45, 48, 67, 74, 64],
       [61, 53, 61, 59, 55, 77],
       [69, 69, 48, 60, 71, 56],
       [51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53],
       [60, 55, 64, 72, 46, 69],
       [65, 75, 75, 51, 75, 67]])

In [16]:
b.ndim

2

In [17]:
b[0]

array([70, 65, 53, 52, 50, 51])

In [18]:
b.ndim



2

In [19]:
b[0]

array([70, 65, 53, 52, 50, 51])

In [23]:
b[:,4]

array([50, 70, 59, 69, 63, 65, 69])

In [24]:
b[1,3]

63

In [28]:
b[2] #2nd row

array([69, 69, 48, 60, 71, 56])

In [29]:
b[:,]

IndexError: index 7 is out of bounds for axis 1 with size 6

In [30]:
np.random.seed(94)
b=np.random.randint(45,78,(7,6))

In [31]:
b

array([[63, 45, 48, 67, 74, 64],
       [61, 53, 61, 59, 55, 77],
       [69, 69, 48, 60, 71, 56],
       [51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53],
       [60, 55, 64, 72, 46, 69],
       [65, 75, 75, 51, 75, 67]])

In [32]:
b[2]#2nd row

array([69, 69, 48, 60, 71, 56])

In [34]:
b[:,4]

array([74, 55, 71, 68, 65, 46, 75])

In [35]:
b[1,3]#1 st row and 3 column position

59

In [38]:
b[1,4]

55

In [39]:
b[2,]

array([69, 69, 48, 60, 71, 56])

In [40]:
b[5]

array([60, 55, 64, 72, 46, 69])

In [42]:
b[2,1:6]

array([69, 48, 60, 71, 56])

In [47]:
array[ row_start : row-end : row-step]

NameError: name 'array' is not defined

In [63]:
b[2:4:2,1:6]

array([[69, 48, 60, 71, 56]])

In [58]:
array [ row_start : row-end : row-step , col_start : col_end : col_step]


NameError: name 'array' is not defined

In [66]:
b[2:5,2:6]

array([[48, 60, 71, 56],
       [59, 47, 68, 77],
       [52, 74, 65, 53]])

In [67]:
b

array([[63, 45, 48, 67, 74, 64],
       [61, 53, 61, 59, 55, 77],
       [69, 69, 48, 60, 71, 56],
       [51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53],
       [60, 55, 64, 72, 46, 69],
       [65, 75, 75, 51, 75, 67]])

In [70]:
b[1:6:2]

array([[61, 53, 61, 59, 55, 77],
       [51, 58, 59, 47, 68, 77],
       [60, 55, 64, 72, 46, 69]])

In [71]:
b[1:6:2, 1:8:3]

array([[53, 55],
       [58, 68],
       [55, 46]])