In [11]:
import pandas as pd
import seaborn as sns
import numpy as np

In [25]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic',
 'anagrams',
 'anagrams',
 'anscombe',
 'anscombe',
 'attention',
 'attention',
 'brain_networks',
 'brain_networks',
 'car_crashes',
 'car_crashes',
 'diamonds',
 'diamonds',
 'dots',
 'dots',
 'dowjones',
 'dowjones',
 'exercise',
 'exercise',
 'flights',
 'flights',
 'fmri',
 'fmri',
 'geyser',
 'geyser',
 'glue',
 'glue',
 'healthexp',
 'healthexp',
 'iris',
 'iris',
 'mpg',
 'mpg',
 'penguins',
 'penguins',
 'planets',
 'planets',
 'seaice',
 'seaice',
 'taxis',
 'taxis',
 'tips',
 'tips',
 'titanic',
 'titanic',
 'anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'plan

In [13]:
k=[2,3,4,5,6,6]

In [14]:
pd.Series(k)

0    2
1    3
2    4
3    5
4    6
5    6
dtype: int64

In [15]:
a=np.random.randint(20,50,(5,4))
a

array([[40, 45, 42, 47],
       [39, 24, 31, 29],
       [35, 27, 33, 38],
       [33, 40, 48, 40],
       [47, 31, 47, 26]])

In [16]:
a.ndim

2

In [17]:
pd.DataFrame(a)

0   1   2   3
0  40  45  42  47
1  39  24  31  29
2  35  27  33  38
3  33  40  48  40
4  47  31  47  26

In [23]:
df1=pd.DataFrame(a,columns=['id','age','marks','height'],index=['A001','A002','A003','A004','A005'])

In [24]:
df1

id  age  marks  height
A001  40   45     42      47
A002  39   24     31      29
A003  35   27     33      38
A004  33   40     48      40
A005  47   31     47      26

In [35]:
df=sns.load_dataset('planets')

In [36]:
df

method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [37]:
type(df)

pandas.core.frame.DataFrame

In [38]:
df.shape[1]

6

In [41]:
df.shape

(1035, 6)

In [42]:
df.columns

Index(['method', 'number', 'orbital_period', 'mass', 'distance', 'year'], dtype='object')

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   method          1035 non-null   object 
 1   number          1035 non-null   int64  
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64  
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB


In [44]:
import seaborn as sns

In [48]:
k=[1.2,2,3,4.5,56,7]

In [49]:
k

[1.2, 2, 3, 4.5, 56, 7]

In [50]:
pd.Series(k)

0     1.2
1     2.0
2     3.0
3     4.5
4    56.0
5     7.0
dtype: float64

In [53]:
'2025/064/21'

'2025/064/21'

In [56]:
'2025/01/21'

'2025/01/21'

In [61]:
df['year'].unique()

array([2006, 2008, 2011, 2007, 2009, 2002, 1996, 2010, 2001, 1995, 2004,
       2012, 2013, 2005, 2000, 2003, 1997, 1999, 2014, 1998, 1989, 1992,
       1994], dtype=int64)

In [62]:
df['mass']

0        7.10
1        2.21
2        2.60
3       19.40
4       10.50
        ...  
1030      NaN
1031      NaN
1032      NaN
1033      NaN
1034      NaN
Name: mass, Length: 1035, dtype: float64

In [63]:
df['year']

0       2006
1       2008
2       2011
3       2007
4       2009
        ... 
1030    2006
1031    2007
1032    2007
1033    2008
1034    2008
Name: year, Length: 1035, dtype: int64

In [64]:
df['orbital_period']

0       269.300000
1       874.774000
2       763.000000
3       326.030000
4       516.220000
           ...    
1030      3.941507
1031      2.615864
1032      3.191524
1033      4.125083
1034      4.187757
Name: orbital_period, Length: 1035, dtype: float64

In [67]:
df['orbital_period'].unique()

array([2.69300000e+02, 8.74774000e+02, 7.63000000e+02, 3.26030000e+02,
       5.16220000e+02, 1.85840000e+02, 1.77340000e+03, 7.98500000e+02,
       9.93300000e+02, 4.52800000e+02, 8.83000000e+02, 3.35100000e+02,
       4.79100000e+02, 1.07800000e+03, 2.39100000e+03, 1.40020000e+04,
       4.23078500e+00, 1.46510000e+01, 4.43800000e+01, 4.90900000e+03,
       7.36540000e-01, 2.61200000e+02, 4.21500000e+00, 3.80210000e+01,
       1.23010000e+02, 1.16688400e+02, 6.91900000e+02, 9.52700000e+02,
       1.81400000e+02,            nan, 1.02200000e+04, 5.76700000e+03,
       3.32100000e+03, 5.57355000e+03, 2.88350000e+03, 2.90000000e+03,
       4.34350000e+03, 5.84000000e+03, 1.91625000e+03, 3.80800000e+02,
       3.23570000e+00, 6.00000000e+03, 2.50200000e+03, 4.17900000e+02,
       5.94900000e+02, 4.28500000e+02, 9.03300000e+02, 1.25100000e+03,
       1.36750000e+02, 5.30320000e+02, 3.18600000e+03, 2.77020000e+02,
       1.87830000e+02, 1.63000000e+03, 3.98450000e+01, 3.31350000e+00,
      

In [68]:
df['orbital_period'].value_counts()

orbital_period
1845.000000    2
428.500000     2
123.000000     2
883.000000     2
10.854092      1
              ..
31.560000      1
197.000000     1
851.800000     1
2231.000000    1
4.187757       1
Name: count, Length: 988, dtype: int64

In [69]:
6433-(43354+9784)

-46705

In [70]:
1035-(513+808)

-286

In [71]:
df['orbital_period'].std()

26014.72830406252

In [72]:
df['orbital_period'].var()

676766088.7341915

In [73]:
df['orbital_period'].mean()

2002.9175960947582

In [74]:
df['orbital_period'].max()

730000.0

In [75]:
df['orbital_period'].min()

0.09070629

In [76]:
df['orbital_period'].median()

39.9795

In [77]:
df['orbital_period'].mode()

0     123.0
1     428.5
2     883.0
3    1845.0
Name: orbital_period, dtype: float64